[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://gestao-indicadores-hospitalares-production.up.railway.app/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"